source 'https://github.com/CocoaPods/Specs.git'

target 'Operative_Example', :exclusive => true do
  pod "Operative", :path => "../"
end

target 'Operative_Tests', :exclusive => true do
  pod "Operative", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
